Vagrant.configure("2") do |config|

    $basebox_name="basebox-win-2019"
    $basebox_hostname="win-2019"
    $src_image_name="StefanScherer/windows_2019"
    $src_image_version="2020.09.22"

    scriptlist = Array[]
    scriptlist = Dir.glob("../packer/provisioners/*").sort    

    config.vm.define "#{$basebox_name}" do |machine|
      machine.vm.box = "#{$src_image_name}"
      machine.vm.box_version = "#{$src_image_version}"
    
      # define guest hostname
      machine.vm.hostname = "#{$basebox_hostname}"

      machine.vm.provider "virtualbox" do |vb|
        vb.name = $basebox_name
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--memory", "1024" ]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--groups", "/basebox-build" ]
        vb.customize ["modifyvm", :id, "--vram", 256 ]
      end

      # disable vbguest update
      machine.vbguest.auto_update = false

      # forwarding ports
      machine.vm.network "forwarded_port", id: "rdp",  auto_correct: true, protocol: "tcp", guest: 3389, host: 33333, host_ip: "127.0.0.1"

      # define synced directory
      machine.vm.synced_folder "../packer/files-prov", "/file-prov"

      # file provisioning
      machine.vm.provision "file", source: "../packer/files-prov", destination: "/Users/vagrant/files-prov"
      
      # shell provisioning
      scriptlist.each { |scriptpath|
        machine.vm.provision :shell do |cfg|
          cfg.name = File.basename(scriptpath)
          cfg.path = scriptpath
        end        
      }

    end   

end
  